version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: tmdb_auth
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
